// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yyijabeyffphcvjlrent.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl5aWphYmV5ZmZwaGN2amxyZW50Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5NDAyODgsImV4cCI6MjA1OTUxNjI4OH0.I0Bz5JkVCxZt37UKPio_CmIj6wiXYHANglfD5emXqC4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);